"""Fachada de compatibilidad: reexporta todo lo que antes vivía en torneos.py.

El código se repartió en un módulo por liga (liga_primera, liga_nacional, liga_federal, ligas_simples,
liga_regional) y temporada.py (estado de la partida y cambio de temporada). La interfaz sigue importando
de acá; el motor (copas, internacional, calendario...) importa de cada módulo directamente.
"""

from liga_primera import (
    ZONA_TAM,
    FECHAS_F1,
    FECHAS_F2,
    TOTAL_FECHAS,
    ZONAS,
    destino,
    total_primera,
    primera_terminada,
    rotulo_p,
    definir_bloque,
    nueva_estructura,
    stats_visibles,
    df_base,
    tabla_general,
    tabla_zona,
    tabla_final,
    iniciar_fase2,
    simular_fecha,
)
from liga_nacional import (
    B_ZONA_TAM,
    B_TAM2,
    B_F1_ZONAL,
    B_F1_INTER,
    B_F1,
    B_F2,
    B_RED,
    B_TOTAL,
    B_ETAPAS,
    B_ZONAS2,
    destino_b1,
    destino_b2,
    total_b,
    rotulo_b,
    nueva_estructura_b,
    tabla_b_f1,
    tabla_b_f2,
    iniciar_fase2_b,
    iniciar_reducido,
    simular_fecha_b,
)
from liga_federal import (
    F_ZONA_TAM,
    F_F2_RONDAS,
    F_RED,
    F_ETAPAS,
    F_MIN,
    F_DESC,
    destino_f1,
    destino_f2,
    rotulo_f,
    nueva_estructura_f,
    tabla_f_grupo,
    tabla_f_f2,
    desempate_campeon_f,
    desempate_descenso_f,
    iniciar_fase2_f,
    iniciar_reducido_f,
    simular_fecha_f,
)
from ligas_simples import (
    destino_pb,
    destino_pc,
    destino_pd,
    nueva_estructura_liga,
    tabla_pb,
    tabla_pc,
    tabla_pd,
    simular_fecha_liga,
)
from liga_regional import (
    REG_LIGA,
    REG_FINAL,
    region_reg,
    nueva_estructura_reg,
    _coef_reg,
    tabla_reg_region,
    _cierre_ligas_reg,
    _jugar_desempates_reg,
    _armar_finales_reg,
    _jugar_pierna_reg,
    rotulo_reg,
    simular_fecha_reg,
)
from temporada import (
    VERSION_ESTADO,
    crear_estado,
    nueva_temporada,
)
