"""Fachada de compatibilidad: reexporta todo lo que antes vivía en vista.py.

El código se repartió por tema (vista_css, vista_base, vista_partidos, vista_ficha, vista_fixture,
vista_tablas, vista_puente, vista_cuadros, vista_copas_int, vista_calendario). Las pestañas siguen
importando de acá, así que no cambian.
"""

from ui.vista.css import (
    CSS,
)
from ui.vista.base import (
    _estado,
    COLOR_ORO,
    COLORES_DESTINO,
    COLORES_ZONA,
    COLORES_B,
    COLORES_F,
    COLOR_COMP,
    esc,
    color_de,
    chip,
    seccion,
    aviso,
    leyenda,
    iniciales,
    crest,
    norm,
    _STOP,
    coincide,
    LEY_ZONAS,
    LEY_DESTINOS,
    LEY_B,
    LEY_F,
    _ISO,
    bandera,
    barra_estado,
)
from ui.vista.partidos import (
    todos_los_partidos,
    _categoria_arg,
    categoria_de,
    marcador_html,
    tanda_html,
    fila_partido_html,
    lista_equipos_html,
    resultado_para,
    pendiente,
    fechas_conocidas_p,
    partidos_fecha_p,
    fechas_conocidas_b,
    partidos_fecha_b,
    fechas_conocidas_f,
    partidos_fecha_f,
    fechas_conocidas_pb,
    partidos_fecha_pb,
    fechas_conocidas_pc,
    partidos_fecha_pc,
    fechas_conocidas_pd,
    partidos_fecha_pd,
    fechas_conocidas_reg,
    partidos_fecha_reg,
    proximo_partido,
)
from ui.vista.ficha import (
    render_ficha,
    ver_equipo,
)
from ui.vista.fixture import (
    render_fecha,
    _mover_fecha,
    vista_fixture,
)
from ui.vista.tablas import (
    ultimos_movs,
    color_mov,
    _COL_NUM,
    _TITULOS,
    _AYUDAS,
    _valor,
    club_link,
    _th,
    tabla_html,
    mostrar_tabla,
    colorear_fase1,
    colorear_destino,
    colorear_b,
    colorear_f,
    colorear_pb,
    colorear_reg,
    colorear_pc,
    colorear_pd,
    rachas,
    card,
    eq_html,
    partido_corto,
    render_movimientos,
)
from ui.vista.puente import (
    _PUENTE_JS,
    _instalar_puente_js,
    _club_elegido,
    puente_clubes,
)
from ui.vista.cuadros import (
    bracket_card,
    bracket_html,
    bracket_html_f,
    _nm_club,
    _fila_final,
    finales_reg_html,
    _kb_card,
    _kb_col,
    _kb_ronda,
    _kb_final,
    _kb,
    cuadro_llave_html,
    cuadro_final_copa_html,
    _ICONO_AVISO,
    avisos_html,
)
from ui.vista.copas_int import (
    _INT_CLAVE,
    _int_pendientes,
    _club_int,
    serie_int_html,
    series_int_html,
    grupos_int_html,
    _kb_card_serie,
    cuadro_int_html,
    grupos_mundial_html,
    _kb_card_mundial,
    cuadro_mundial_html,
)
from ui.vista.calendario import (
    _cal_partidos,
    _cal_rotulo,
    eventos_calendario,
    _cal_res,
    calendario_mes_html,
)
